# Generated by Django 6.0.2 on 2026-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskymodel',
            options={'verbose_name': 'Tasky Model', 'verbose_name_plural': 'Tasky Model'},
        ),
        migrations.AlterField(
            model_name='taskymodel',
            name='complished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskymodel',
            name='task',
            field=models.TextField(max_length=200),
        ),
    ]
