# Generated by Django 6.0.2 on 2026-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskyapp', '0002_alter_taskymodel_options_alter_taskymodel_complished_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplishedTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=70)),
                ('priority', models.IntegerField()),
                ('task', models.CharField(max_length=200)),
            ],
        ),
    ]
