# Generated by Django 6.0.2 on 2026-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskyapp', '0003_complishedtaskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskymodel',
            name='complished',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
